VAGRANTFILE_API_VERSION = "2"

# Install role dependencies
system("
    if [ #{ARGV[0]} = 'up' ]; then
        echo 'Installing role dependencies'
        ./install_role_requirements.sh
    fi
")

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

#------------------------------------------------------------------------------
# Common settings for all VMs

    config.vm.synced_folder "shared", "/home/vagrant/shared"
    config.vm.box = "bento/ubuntu-16.04"

#------------------------------------------------------------------------------

    config.vm.define "example" do |example|
        example.vm.hostname = 'example'

        example.vm.provider :virtualbox do |vb|
            # Force more aggressive time updates, needed for when host machine sleeps
            vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]

            # Set memory lower
            vb.memory = 1024
            vb.cpus = 2
        end

        example.vm.provision "ansible" do |ansible|
            ansible.groups = {
                 "vagrant_managed" => ["example"]
             }
            ansible.verbose = "vv"
            ansible.playbook = "example.yml"
        end
    end

end
